services:
  # 1. The Backend (Docker Container)
  - type: web
    name: lottery-backend
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /wins
    envVars:
      - key: DATABASE_PATH
        value: /tmp/db.db # Writes to temporary disk (Resets on restart)
      - key: DENO_ENV
        value: production


